apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: altoroj
  name: altoroj
  namespace: altoroj
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: management
    port: 9990
    protocol: TCP
    targetPort: 9990
  selector:
    app: altoroj
  type: NodePort
status:
  loadBalancer: {}
